### ISSUE TITLE
Zentao 17.5版本安装插件后报错

### ISSUE THREAD

**Issue by loveafa** [luzi2000/zentao-ldap#1]
信息如下：
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting function (T_FUNCTION) or const (T_CONST) in /www/zentaopms/tmp/model/open/rnd/tmpuser.php on line 20

23:19:48 syntax error, unexpected 'class' (T_CLASS), expecting function (T_FUNCTION) or const (T_CONST) in /www/zentaopms/tmp/model/open/rnd/tmpuser.php on line 20 when visiting ?tid=7ow5tagg

**Comment by blfish008** [comment]
一样的错误，作者没有这个问题吗？

**Comment by blfish008** [comment]
@luzi2000

**Comment by luzi2000** [comment]
我的正常啊，晚点我装个独立的包看看，这个报错看上去不象是插件的问题

**Comment by blfish008** [comment]
对啊，导入后/www/zentaopms/tmp/model/open/rnd/tmpuser.php这个文件不正常了
```php
<?php
global $app;
helper::import($app->getModulePath('', 'user') . 'model.php');
class tmpExtuserModel extends userModel
{
/**
 * Get user by his account.
 *
 * @param mixed $account
 * @access public
 * @return object           the user.
 */
public function getByAccount($account)
{
    return $this->dao->select('*')->from(TABLE_USER)
        ->beginIF(validater::checkEmail($account))->where('email')->eq($account)->fi()
        ->beginIF(!validater::checkEmail($account))->where('account')->eq($account)->fi()
        ->andWhere('deleted')->eq('0')
        ->fetch();
}class ldapModel extends model
{
    public function identify($host, $dn, $pwd)
    {
        $ret = '';
        $ds = ldap_connect($host);
        if ($ds) {
            ldap_set_option($ds, LDAP_OPT_PROTOCOL_VERSION, 3);
            ldap_bind($ds, $dn, $pwd);

            $ret = ldap_error($ds);
            ldap_close($ds);
        } else {
            $ret = ldap_error($ds);
        }

        return $ret;
    }

    public function getUsers($config)
    {
        $ds = ldap_connect($config->host);
        if ($ds) {
            ldap_set_option($ds, LDAP_OPT_PROTOCOL_VERSION, 3);
            ldap_bind($ds, $config->bindDN, $config->bindPWD);

            $attrs = [$config->uid, $config->mail, $config->name];

            $rlt = ldap_search($ds, $config->baseDN, $config->searchFilter, $attrs);
            $data = ldap_get_entries($ds, $rlt);
            return $data;
        }

        return null;
    }

    public function sync2db($config)
    {
        $ldapUsers = $this->getUsers($config);
        $user = new stdclass();
        $account = '';
        $i=0;
        for (; $i < $ldapUsers['count']; $i++) {
            $user->account = $ldapUsers[$i][$config->uid][0];
            $user->email = $ldapUsers[$i][$config->mail][0];
            $user->realname = $ldapUsers[$i][$config->name][0];

            $account = $this->dao->select('*')->from(TABLE_USER)->where('account')->eq($user->account)->fetch('account');
            if ($account == $user->account) {
                $this->dao->update(TABLE_USER)->data($user)->where('account')->eq($user->account)->autoCheck()->exec();
            } else {
                $this->dao->insert(TABLE_USER)->data($user)->autoCheck()->exec();
            }

            if (dao::isError()) {
                echo js::error(dao::getError());
                die(js::reload('parent'));
            }
        }

        return $i;
    }
}
//**//
```

**Comment by blfish008** [comment]
对啊，导入后/www/zentaopms/tmp/model/open/rnd/tmpuser.php这个文件不正常了
`<?php
global $app;
helper::import($app->getModulePath('', 'user') . 'model.php');
class tmpExtuserModel extends userModel
{
/**
 * Get user by his account.
 *
 * @param mixed $account
 * @access public
 * @return object           the user.
 */
public function getByAccount($account)
{
    return $this->dao->select('*')->from(TABLE_USER)
        ->beginIF(validater::checkEmail($account))->where('email')->eq($account)->fi()
        ->beginIF(!validater::checkEmail($account))->where('account')->eq($account)->fi()
        ->andWhere('deleted')->eq('0')
        ->fetch();
}class ldapModel extends model
{
    public function identify($host, $dn, $pwd)
    {
        $ret = '';
        $ds = ldap_connect($host);
        if ($ds) {
            ldap_set_option($ds, LDAP_OPT_PROTOCOL_VERSION, 3);
            ldap_bind($ds, $dn, $pwd);

            $ret = ldap_error($ds);
            ldap_close($ds);
        } else {
            $ret = ldap_error($ds);
        }

        return $ret;
    }

    public function getUsers($config)
    {
        $ds = ldap_connect($config->host);
        if ($ds) {
            ldap_set_option($ds, LDAP_OPT_PROTOCOL_VERSION, 3);
            ldap_bind($ds, $config->bindDN, $config->bindPWD);

            $attrs = [$config->uid, $config->mail, $config->name];

            $rlt = ldap_search($ds, $config->baseDN, $config->searchFilter, $attrs);
            $data = ldap_get_entries($ds, $rlt);
            return $data;
        }

        return null;
    }

    public function sync2db($config)
    {
        $ldapUsers = $this->getUsers($config);
        $user = new stdclass();
        $account = '';
        $i=0;
        for (; $i < $ldapUsers['count']; $i++) {
            $user->account = $ldapUsers[$i][$config->uid][0];
            $user->email = $ldapUsers[$i][$config->mail][0];
            $user->realname = $ldapUsers[$i][$config->name][0];

            $account = $this->dao->select('*')->from(TABLE_USER)->where('account')->eq($user->account)->fetch('account');
            if ($account == $user->account) {
                $this->dao->update(TABLE_USER)->data($user)->where('account')->eq($user->account)->autoCheck()->exec();
            } else {
                $this->dao->insert(TABLE_USER)->data($user)->autoCheck()->exec();
            }

            if (dao::isError()) {
                echo js::error(dao::getError());
                die(js::reload('parent'));
            }
        }

        return $i;
    }
}
//**//
`

**Comment by blfish008** [comment]
@luzi2000

**Comment by luzi2000** [comment]
请问下你确认你的版本是17.5么，还有是用的一体包还是用的源码包，我用的源码包，并没有生成tmpuser.php这个文件

**Comment by luzi2000** [comment]
我在我自己的机器上试过是没问题的，用的openldap，没试过微软的ldap，并且试了17.6.2版本也是可以的

**Comment by luzi2000** [comment]
可以把这个tmpuser备份到其它位置后删除试试

**Comment by ACTom** [comment]
应该是/extension/custom/user/ext/model/identify.php 这个文件的问题，禅道会把这个文件内容自动复制到/tmp/model/open/rnd/tmpuser.php文件，我尝试把identify.php中的class ldapModel extends model删掉，倒是不报错了，而且可以顺利的配置、同步用户，但是，登录的时候会报错。
对比了下/extension/custom/user/ext/model/identify.php和/extension/custom/ldap/model.php内容是一致的，所以猜测是不是/extension/custom/user/ext/model/identify.php这个文件传错了？

**Comment by blfish008** [comment]
和楼上说的一样，应该是传的有问题，删了tmpuser.php这个没有用

**Comment by blfish008** [comment]
@luzi2000 我用的docker版17.5

**Comment by luzi2000** [comment]
对比了下本地代码 ，之前可能是提交错了。。。报欠几位，这回再看看呢

**Comment by blfish008** [comment]
@luzi2000 更新一下啊，谢谢了

**Comment by ACTom** [comment]
> @luzi2000 更新一下啊，谢谢了

作者已经更新了，可以用，不过如果是不在BaseDN下的用户登录会找不到，头疼。

**Comment by luzi2000** [comment]
这个是你ldap配置的问题吧

**Comment by luzi2000** [comment]
源来最早的ldap插件的代码我基本上没改，只是适配了新版本

**Comment by blfish008** [comment]
> 这个是你ldap配置的问题吧



> > @luzi2000 更新一下啊，谢谢了
> 
> 作者已经更新了，可以用，不过如果是不在BaseDN下的用户登录会找不到，头疼。

我这BaseDN下的也不行啊。。导入没问题，第一次登录提示用户密码错误，登录几次提示密码错误，还有3次机会，确定ldap配置在旧版本里是能用的啊
@luzi2000

**Comment by luzi2000** [comment]
ldap配置我没怎么搞过，你得确认你的过滤器是对的，我理解一般情况下都可以通过过滤器来配置出来

**Comment by luzi2000** [comment]
basedn只是你登陆用的参数吧

**Comment by cuichuankai** [comment]
我的17.5也是导入没问题，查看用户都已经导入到禅道里了，但是登录提示用户密码错误。

**Comment by blfish008** [comment]
> basedn只是你登陆用的参数吧

解决了，谢谢了
你用的是老版的改的，用我之前用的替换调你里面的model.php和identify.php就好了

**Comment by cuichuankai** [comment]
> > basedn只是你登陆用的参数吧
> 
> 解决了，谢谢了 你用的是老版的改的，用我之前用的替换调你里面的model.php和identify.php就好了

怎么解决的，能否发一个包？谢谢。

**Comment by cuichuankai** [comment]
> > basedn只是你登陆用的参数吧
> 
> 解决了，谢谢了 你用的是老版的改的，用我之前用的替换调你里面的model.php和identify.php就好了

多谢提醒，我也搞定了！

**Comment by cuichuankai** [comment]
diff -r zentao-ldap-master/extension/custom/ldap/model.php zentao-ldap-master-new/extension/custom/ldap/model.php
20a21,42
>     public function getUserDn($config, $account){
>         $ret = null;
>         $ds = ldap_connect($config->host);
>         if ($ds) {
>             ldap_set_option($ds,LDAP_OPT_PROTOCOL_VERSION,3);
>             ldap_bind($ds, $config->bindDN, $config->bindPWD);
>             $filter = "($config->uid=$account)";
>             $rlt = ldap_search($ds, $config->baseDN, $filter);
>             $count=ldap_count_entries($ds, $rlt);
>
>             if($count > 0){
>                 $data = ldap_get_entries($ds, $rlt);
>                 $ret = $data[0]['dn'];
>                 $str = serialize($data);
>             }
>
>             ldap_unbind($ds);
>             ldap_close($ds);
>         }
>         return $ret;
>     }
>
diff -r zentao-ldap-master/extension/custom/user/ext/model/identify.php zentao-ldap-master-new/extension/custom/user/ext/model/identify.php
14c14
<         	$ldap_account = $this->config->ldap->uid.'='.$account.','.$this->config->ldap->baseDN;
---
>         	$ldap_account = $ldap->getUserDn($this->config->ldap, $account);

**Comment by cuichuankai** [comment]
model.php新加方法getUserDn，identify.php里获取把$ldap_account = $this->config->ldap->uid.'='.$account.','.$this->config->ldap->baseDN;修改为$ldap_account = $ldap->getUserDn($this->config->ldap, $account);

**Comment by luzi2000** [comment]
我改下

**Comment by luzi2000** [comment]
按你说的改了下，看看还有啥问题么

**Comment by cuichuankai** [comment]
17.7可以用没问题

**Comment by luzi2000** [comment]
感谢各位，如果有问题再处理
